Repository ezcater/recipe, pull requests merged in 2022-02, with the labels that each got.

#756 revert storybook dependency upgrades to fix ghpages deployment builds
  .changeset/many-dots-warn.md
  jest.config.js
  package-lock.json
  package.json
  src/components/EzNavigation/EzNavigation.stories.tsx
Labels: ghpages

#742 feat: all onFocus callback events to EzField type="date"
  .changeset/lovely-nails-speak.md
  src/components/EzField/EzDateInput.tsx
  src/components/EzField/__tests__/EzField.date.test.tsx
Labels: deploy

#762 feat: EzIcon component
  .changeset/rare-glasses-grow.md
  .changeset/tame-ears-invite.md
  doc-site/package-lock.json
  doc-site/package.json
  doc-site/src/components/Markdown.js
  doc-site/static/images/preview/EzIcon.png
  package-lock.json
  package.json
  playroom/useScope.js
  src/components/EzIcon/EzIcon.md
  src/components/EzIcon/EzIcon.preview.md
  src/components/EzIcon/EzIcon.theme.config.ts
  src/components/EzIcon/EzIcon.tsx
  src/components/EzIcon/EzIcon.types.ts
  src/components/EzIcon/EzIconMocks.tsx
  src/components/EzIcon/Implementations/EzIconEzCater/EzIconEzCater.tsx
  src/components/EzIcon/Implementations/EzIconFontAwesome/EzIconFontAwesome.tsx
  src/components/EzIcon/Implementations/EzIconMui/EzIconMui.tsx
  src/components/EzIcon/__tests__/EzIcon.test.tsx
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-decorative-icons-snap.png
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-ezcater-icon-snap.png
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-font-awesome-icon-snap.png
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-icon-color-snap.png
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-icon-size-snap.png
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-semantic-icons-snap.png
  src/components/EzIcon/__tests__/__image_snapshots__/chrome-desktop-svg-icon-snap.png
  src/components/EzIcon/index.tsx
  src/components/index.tsx
  src/components/theme.config.ts
  src/stories/scope.tsx
Labels: enhancement, deploy

#763 feat: EzRating component
  .changeset/fast-trees-warn.md
  doc-site/package-lock.json
  doc-site/package.json
  doc-site/src/components/Markdown.js
  doc-site/static/images/preview/EzRating.png
  playroom/useScope.js
  src/components/EzIcon/EzIconMocks.tsx
  src/components/EzRating/EzRating.md
  src/components/EzRating/EzRating.preview.md
  src/components/EzRating/EzRating.tsx
  src/components/EzRating/EzRating.types.ts
  src/components/EzRating/Implementations/EzRatingCustom/EzRatingCustom.tsx
  src/components/EzRating/__tests__/EzRating.test.tsx
  src/components/EzRating/__tests__/__image_snapshots__/chrome-desktop-basic-rating-snap.png
  src/components/EzRating/__tests__/__image_snapshots__/chrome-desktop-color-snap.png
  src/components/EzRating/__tests__/__image_snapshots__/chrome-desktop-size-snap.png
  src/components/EzRating/index.tsx
  src/components/index.tsx
  src/stories/scope.tsx
Labels: enhancement

#764 feat: add EzProgress component
  .changeset/thick-nails-juggle.md
  doc-site/static/images/preview/EzProgress.png
  src/components/EzProgress/EzProgress.md
  src/components/EzProgress/EzProgress.preview.md
  src/components/EzProgress/EzProgress.tsx
  src/components/EzProgress/EzProgress.types.ts
  src/components/EzProgress/Implementations/EzProgressMui/EzProgressMui.tsx
  src/components/EzProgress/__tests__/EzProgress.test.tsx
  src/components/EzProgress/__tests__/__image_snapshots__/chrome-desktop-custom-progress-snap.png
  src/components/EzProgress/__tests__/__image_snapshots__/chrome-desktop-empty-progress-snap.png
  src/components/EzProgress/__tests__/__image_snapshots__/chrome-desktop-goal-progress-snap.png
  src/components/EzProgress/index.tsx
  src/components/index.tsx
  src/components/theme.config.ts
Labels: enhancement, deploy
